name: Trigger update docs workflow on ti.net repo
on:
  release:
    types:
      - published
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Trigger remote workflow to update docs
        run: |
          repo_owner="mattsmida"
          repo_name="ti.net"
          event_type="trigger-workflow-update-docs"
          service="the-push-service"
          version="${{ github.event.release.tag_name }}"

          # Collect all documentation files
          doc_filenames=$(find doc/man1 doc/man7 -type f)

          # Format doc_filenames with single quotes and commas
          doc_filenames="[ $(echo $doc_files | sed "s/\S\+/\"&\",/g; s/,$//") ]"

          base64_encoded_files=()
          while IFS= read -r filename; do
              base64_encoded_file=$(base64 "$filename" | tr -d '\n')
              base64_encoded_files+=("\"$base64_encoded_file\"")
          done <<< "$doc_filenames"

          # Format encoded_file_contents with quotes and commas
          encoded_file_contents="$(for elem in "${base64_encoded_files[@]}"; do echo "$elem,"; done)"

          encoded_file_contents="[ $(echo $encoded_file_contents | sed 's/,$//') ]"

          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
              -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true, \"doc_filenames\": $doc_filenames, \"encoded_file_contents\": $encoded_file_contents}}"
